export const ROOT_WINDOW_TITLE = "Chat 1";
export const ROOT_WINDOW_X = 88;
export const ROOT_WINDOW_Y = 72;
export const WINDOW_WIDTH = 560;
export const WINDOW_HEIGHT = 840;
export const WINDOW_GAP = 128;
export const CHILD_VERTICAL_STAGGER = 56;
export const MIN_WINDOW_WIDTH = 420;
export const MIN_WINDOW_HEIGHT = 360;
